// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yuqvtucvqivvvpcfflhq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1cXZ0dWN2cWl2dnZwY2ZmbGhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMDA4NDYsImV4cCI6MjA3MzY3Njg0Nn0.k1n8odJZ4uEQXseS2627qYYPqjC0n2gEU07Kxh5de40";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});